# Generated by Django 4.2 on 2023-05-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_tag_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('Draft', 'Draft')], max_length=200),
        ),
    ]
