# Generated by Django 4.2 on 2023-05-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
